spring.config.additional-location=file:src/properties/application.properties
spring.thymeleaf.prefix=file:src/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=false
spring.thymeleaf.cache=false
server.port=8080